# Copyright 2019 Tecnativa - Ernesto Tejeda
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
from odoo import api, models
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = "sale.order"

    def _get_copiable_order_lines(self):
        self.ensure_one()
        res = super()._get_copiable_order_lines()
        res = res.filtered(
            lambda x, order=self: x.pack_parent_line_id.order_id != order
        )
        # Non-detailed modifiable packs expand into: collapse_composition section +
        # pack product line + standalone component lines. On copy, only the pack
        # product line should be carried over — the section and components are
        # regenerated by action_transform_pack_to_lines at create time.
        lines_to_exclude = self.env["sale.order.line"]
        for pack_line in res.filtered(
            lambda line: not line.display_type
            and line.product_id.pack_ok
            and line.pack_type == "non_detailed"
            and line.product_id.pack_modifiable
        ):
            lines_to_exclude |= pack_line._get_non_detailed_pack_section_line()
            lines_to_exclude |= pack_line._get_non_detailed_pack_component_lines()
        return res - lines_to_exclude

    @api.onchange("order_line")
    def check_pack_line_unlink(self):
        """At least on embeded tree editable view odoo returns a recordset on
        _origin.order_line only when lines are unlinked and this is exactly
        what we need
        """
        origin_line_ids = self._origin.order_line.ids
        line_ids = self.order_line.ids
        removed_line_ids = list(set(origin_line_ids) - set(line_ids))
        removed_line = self.env["sale.order.line"].browse(removed_line_ids)
        if removed_line.filtered(
            lambda x: x.pack_parent_line_id
            and not x.pack_parent_line_id.product_id.pack_modifiable
        ):
            raise UserError(
                self.env._(
                    "You cannot delete this line because is part of a pack in"
                    " this sale order. In order to delete this line you need to"
                    " delete the pack itself"
                )
            )

    def write(self, vals):
        if "order_line" in vals:
            to_delete_ids = [e[1] for e in vals["order_line"] if e[0] == 2]
            subpacks_to_delete_ids = (
                self.env["sale.order.line"]
                .search(
                    [("id", "child_of", to_delete_ids), ("id", "not in", to_delete_ids)]
                )
                .ids
            )
            if subpacks_to_delete_ids:
                for cmd in vals["order_line"]:
                    if cmd[1] in subpacks_to_delete_ids:
                        if cmd[0] != 2:
                            cmd[0] = 2
                        subpacks_to_delete_ids.remove(cmd[1])
                for to_delete_id in subpacks_to_delete_ids:
                    vals["order_line"].append([2, to_delete_id, False])
            if to_delete_ids:
                # In the case of you modify the list of order lines
                # Then you switch the tab of your browser
                # That will trigger an invisible write operation
                # even if the onchange triggered a raise
                line_to_check = self.env["sale.order.line"].search(
                    [("pack_child_line_ids", "in", to_delete_ids)]
                )
                for line in line_to_check:
                    if not line.product_id.pack_modifiable:
                        raise UserError(
                            self.env._(
                                "You cannot delete this line because is part of a pack"
                                " in this sale order. In order to delete this line you"
                                " need to delete the pack itself"
                            )
                        )
        return super().write(vals)

    def _get_update_prices_lines(self):
        res = super()._get_update_prices_lines()
        return res.filtered(
            lambda line: not line.pack_parent_line_id
            or line.pack_parent_line_id.pack_component_price == "detailed"
        )

    def _update_order_line_info(self, product_id, quantity, **kwargs):
        """For non-detailed modifiable packs, skip the auto-transform during
        create so core can safely call _get_discounted_price() on the singleton.
        After getting the price, we trigger the transformation manually."""
        product = self.env["product.product"].browse(product_id)
        is_non_detailed_modifiable = (
            product.pack_ok
            and product.pack_type == "non_detailed"
            and product.pack_modifiable
        )
        if not is_non_detailed_modifiable:
            return super()._update_order_line_info(product_id, quantity, **kwargs)

        if not kwargs.get("section_id"):
            existing_pack_lines = self.order_line.filtered(
                lambda line: not line.display_type
                and line.product_id.id == product_id
                and line.product_id.pack_ok
                and line.pack_type == "non_detailed"
                and line.product_id.pack_modifiable
            )
            if existing_pack_lines:
                # Catalog passes section_id=False by default. If the pack product
                # already lives under a section, route the update to that section
                # so quantity is updated instead of creating a duplicate group.
                target_line = existing_pack_lines.sorted(
                    key=lambda line: (line.sequence, line.id)
                )[-1]
                kwargs["section_id"] = target_line.get_parent_section_line().id

        existing_line_ids = set(self.order_line.ids)
        price = super(
            SaleOrder, self.with_context(skip_non_detailed_pack_transform=True)
        )._update_order_line_info(product_id, quantity, **kwargs)
        # Transform only lines created by this operation. Existing transformed
        # lines may only need quantity sync when the same product is added again.
        new_line_ids = set(self.order_line.ids) - existing_line_ids
        pack_lines = self.order_line.filtered(
            lambda line: line.id in new_line_ids
            and line.product_id.id == product_id
            and line.product_id.pack_ok
            and line.pack_type == "non_detailed"
            and line.product_id.pack_modifiable
        )
        for line in pack_lines:
            line.action_transform_pack_to_lines()
        return price
